/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.38.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`get_activity_logs`]
#[derive(Clone, Debug)]
pub struct GetActivityLogsParams {
    /// Event type(s) to include in the response. Can have multiple values separated by comma. All events are returned by default.
    pub events: Option<String>,
    /// Unix timestamp of the least recent event to include. This param defaults to one year ago if unspecified.
    pub start_time: Option<f64>,
    /// Unix timestamp of the most recent event to include. This param defaults to the current timestamp if unspecified.
    pub end_time: Option<f64>,
    /// Maximum number of events to return. This param defaults to 1000 if unspecified.
    pub limit: Option<f64>,
    /// Event order by timestamp. This param can be either \"asc\" (default) or \"desc\".
    pub order: Option<String>,
}

/// struct for typed errors of method [`get_activity_logs`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetActivityLogsError {
    Status400(models::InlineObject41),
    Status401(models::InlineObject42),
    Status403(models::InlineObject44),
    Status429(models::InlineObject48),
    Status500(models::InlineObject51),
    UnknownValue(serde_json::Value),
}

/// Returns a list of activity log events
pub async fn get_activity_logs(
    configuration: &configuration::Configuration,
    params: GetActivityLogsParams,
) -> Result<models::InlineObject24, Error<GetActivityLogsError>> {
    let uri_str = format!("{}/v1/activity_logs", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.events {
        req_builder = req_builder.query(&[("events", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.start_time {
        req_builder = req_builder.query(&[("start_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.end_time {
        req_builder = req_builder.query(&[("end_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.order {
        req_builder = req_builder.query(&[("order", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject24`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject24`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetActivityLogsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
