/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`delete_comment_reaction`]
#[derive(Clone, Debug)]
pub struct DeleteCommentReactionParams {
    /// File to delete comment reaction from. This can be a file key or branch key. Use `GET /v1/files/:key` with the `branch_data` query param to get the branch key.
    pub file_key: String,
    /// ID of comment to delete reaction from.
    pub comment_id: String,
    pub emoji: String,
}

/// struct for passing parameters to the method [`get_comment_reactions`]
#[derive(Clone, Debug)]
pub struct GetCommentReactionsParams {
    /// File to get comment containing reactions from. This can be a file key or branch key. Use `GET /v1/files/:key` with the `branch_data` query param to get the branch key.
    pub file_key: String,
    /// ID of comment to get reactions from.
    pub comment_id: String,
    /// Cursor for pagination, retrieved from the response of the previous call.
    pub cursor: Option<String>,
}

/// struct for passing parameters to the method [`post_comment_reaction`]
#[derive(Clone, Debug)]
pub struct PostCommentReactionParams {
    /// File to post comment reactions to. This can be a file key or branch key. Use `GET /v1/files/:key` with the `branch_data` query param to get the branch key.
    pub file_key: String,
    /// ID of comment to react to.
    pub comment_id: String,
    /// Reaction to post.
    pub post_comment_reaction_request: models::PostCommentReactionRequest,
}

/// struct for typed errors of method [`delete_comment_reaction`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteCommentReactionError {
    Status403(models::InlineObject49),
    Status404(models::InlineObject51),
    Status429(models::InlineObject53),
    Status500(models::InlineObject56),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_comment_reactions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCommentReactionsError {
    Status403(models::InlineObject49),
    Status404(models::InlineObject51),
    Status429(models::InlineObject53),
    Status500(models::InlineObject56),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_comment_reaction`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostCommentReactionError {
    Status400(models::InlineObject47),
    Status403(models::InlineObject49),
    Status404(models::InlineObject51),
    Status429(models::InlineObject53),
    Status500(models::InlineObject56),
    UnknownValue(serde_json::Value),
}

/// Deletes a specific comment reaction. Only the person who made the reaction is allowed to delete it.
pub async fn delete_comment_reaction(
    configuration: &configuration::Configuration,
    params: DeleteCommentReactionParams,
) -> Result<models::InlineObject14, Error<DeleteCommentReactionError>> {
    let uri_str = format!(
        "{}/v1/files/{file_key}/comments/{comment_id}/reactions",
        configuration.base_path,
        file_key = crate::apis::urlencode(params.file_key),
        comment_id = crate::apis::urlencode(params.comment_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    req_builder = req_builder.query(&[("emoji", &params.emoji.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject14`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject14`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteCommentReactionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Gets a paginated list of reactions left on the comment.
pub async fn get_comment_reactions(
    configuration: &configuration::Configuration,
    params: GetCommentReactionsParams,
) -> Result<models::InlineObject15, Error<GetCommentReactionsError>> {
    let uri_str = format!(
        "{}/v1/files/{file_key}/comments/{comment_id}/reactions",
        configuration.base_path,
        file_key = crate::apis::urlencode(params.file_key),
        comment_id = crate::apis::urlencode(params.comment_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject15`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject15`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetCommentReactionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Posts a new comment reaction on a file comment.
pub async fn post_comment_reaction(
    configuration: &configuration::Configuration,
    params: PostCommentReactionParams,
) -> Result<models::InlineObject14, Error<PostCommentReactionError>> {
    let uri_str = format!(
        "{}/v1/files/{file_key}/comments/{comment_id}/reactions",
        configuration.base_path,
        file_key = crate::apis::urlencode(params.file_key),
        comment_id = crate::apis::urlencode(params.comment_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };
    req_builder = req_builder.json(&params.post_comment_reaction_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject14`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject14`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostCommentReactionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
