/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`get_component_set`]
#[derive(Clone, Debug)]
pub struct GetComponentSetParams {
    /// The unique identifier of the component set.
    pub key: String,
}

/// struct for passing parameters to the method [`get_file_component_sets`]
#[derive(Clone, Debug)]
pub struct GetFileComponentSetsParams {
    /// File to list component sets from. This must be a main file key, not a branch key, as it is not possible to publish from branches.
    pub file_key: String,
}

/// struct for passing parameters to the method [`get_team_component_sets`]
#[derive(Clone, Debug)]
pub struct GetTeamComponentSetsParams {
    /// Id of the team to list component sets from.
    pub team_id: String,
    /// Number of items to return in a paged list of results. Defaults to 30.
    pub page_size: Option<f64>,
    /// Cursor indicating which id after which to start retrieving component sets for. Exclusive with before. The cursor value is an internally tracked integer that doesn't correspond to any Ids.
    pub after: Option<f64>,
    /// Cursor indicating which id before which to start retrieving component sets for. Exclusive with after. The cursor value is an internally tracked integer that doesn't correspond to any Ids.
    pub before: Option<f64>,
}

/// struct for typed errors of method [`get_component_set`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetComponentSetError {
    Status400(models::InlineObject46),
    Status403(models::InlineObject49),
    Status404(models::InlineObject52),
    Status429(models::InlineObject53),
    Status500(models::InlineObject56),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_file_component_sets`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetFileComponentSetsError {
    Status400(models::InlineObject46),
    Status403(models::InlineObject49),
    Status404(models::InlineObject52),
    Status429(models::InlineObject53),
    Status500(models::InlineObject56),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_team_component_sets`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTeamComponentSetsError {
    Status400(models::InlineObject46),
    Status403(models::InlineObject49),
    Status404(models::InlineObject52),
    Status429(models::InlineObject53),
    Status500(models::InlineObject56),
    UnknownValue(serde_json::Value),
}

/// Get metadata on a published component set by key.
pub async fn get_component_set(
    configuration: &configuration::Configuration,
    params: GetComponentSetParams,
) -> Result<models::InlineObject22, Error<GetComponentSetError>> {
    let uri_str = format!(
        "{}/v1/component_sets/{key}",
        configuration.base_path,
        key = crate::apis::urlencode(params.key)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject22`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject22`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetComponentSetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get a list of published component sets within a file library.
pub async fn get_file_component_sets(
    configuration: &configuration::Configuration,
    params: GetFileComponentSetsParams,
) -> Result<models::InlineObject21, Error<GetFileComponentSetsError>> {
    let uri_str = format!(
        "{}/v1/files/{file_key}/component_sets",
        configuration.base_path,
        file_key = crate::apis::urlencode(params.file_key)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject21`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject21`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetFileComponentSetsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get a paginated list of published component sets within a team library.
pub async fn get_team_component_sets(
    configuration: &configuration::Configuration,
    params: GetTeamComponentSetsParams,
) -> Result<models::InlineObject20, Error<GetTeamComponentSetsError>> {
    let uri_str = format!(
        "{}/v1/teams/{team_id}/component_sets",
        configuration.base_path,
        team_id = crate::apis::urlencode(params.team_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.page_size {
        req_builder = req_builder.query(&[("page_size", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.after {
        req_builder = req_builder.query(&[("after", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.before {
        req_builder = req_builder.query(&[("before", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject20`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject20`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetTeamComponentSetsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
