/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.38.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`delete_dev_resource`]
#[derive(Clone, Debug)]
pub struct DeleteDevResourceParams {
    /// The file to delete the dev resource from. This must be a main file key, not a branch key.
    pub file_key: String,
    /// The id of the dev resource to delete.
    pub dev_resource_id: String,
}

/// struct for passing parameters to the method [`get_dev_resources`]
#[derive(Clone, Debug)]
pub struct GetDevResourcesParams {
    /// The file to get the dev resources from. This must be a main file key, not a branch key.
    pub file_key: String,
    /// Comma separated list of nodes that you care about in the document. If specified, only dev resources attached to these nodes will be returned. If not specified, all dev resources in the file will be returned.
    pub node_ids: Option<String>,
}

/// struct for passing parameters to the method [`post_dev_resources`]
#[derive(Clone, Debug)]
pub struct PostDevResourcesParams {
    /// A list of dev resources that you want to create.
    pub post_dev_resources_request: models::PostDevResourcesRequest,
}

/// struct for passing parameters to the method [`put_dev_resources`]
#[derive(Clone, Debug)]
pub struct PutDevResourcesParams {
    /// A list of dev resources that you want to update.
    pub put_dev_resources_request: models::PutDevResourcesRequest,
}

/// struct for typed errors of method [`delete_dev_resource`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteDevResourceError {
    Status401(models::InlineObject42),
    Status403(models::InlineObject44),
    Status404(models::InlineObject46),
    Status429(models::InlineObject48),
    Status500(models::InlineObject51),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_dev_resources`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetDevResourcesError {
    Status400(models::InlineObject41),
    Status401(models::InlineObject42),
    Status403(models::InlineObject44),
    Status404(models::InlineObject46),
    Status429(models::InlineObject48),
    Status500(models::InlineObject51),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_dev_resources`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostDevResourcesError {
    Status400(models::InlineObject41),
    Status401(models::InlineObject42),
    Status403(models::InlineObject44),
    Status429(models::InlineObject48),
    Status500(models::InlineObject51),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`put_dev_resources`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PutDevResourcesError {
    Status400(models::InlineObject41),
    Status401(models::InlineObject42),
    Status403(models::InlineObject44),
    Status429(models::InlineObject48),
    Status500(models::InlineObject51),
    UnknownValue(serde_json::Value),
}

/// Delete a dev resource from a file
pub async fn delete_dev_resource(
    configuration: &configuration::Configuration,
    params: DeleteDevResourceParams,
) -> Result<(), Error<DeleteDevResourceError>> {
    let uri_str = format!(
        "{}/v1/files/{file_key}/dev_resources/{dev_resource_id}",
        configuration.base_path,
        file_key = crate::apis::urlencode(params.file_key),
        dev_resource_id = crate::apis::urlencode(params.dev_resource_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteDevResourceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get dev resources in a file
pub async fn get_dev_resources(
    configuration: &configuration::Configuration,
    params: GetDevResourcesParams,
) -> Result<models::InlineObject30, Error<GetDevResourcesError>> {
    let uri_str = format!(
        "{}/v1/files/{file_key}/dev_resources",
        configuration.base_path,
        file_key = crate::apis::urlencode(params.file_key)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.node_ids {
        req_builder = req_builder.query(&[("node_ids", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject30`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject30`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetDevResourcesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Bulk create dev resources across multiple files. Dev resources that are successfully created will show up in the links_created array in the response.  If there are any dev resources that cannot be created, you may still get a 200 response. These resources will show up in the errors array. Some reasons a dev resource cannot be created include:  - Resource points to a `file_key` that cannot be found. - The node already has the maximum of 10 dev resources. - Another dev resource for the node has the same url.
pub async fn post_dev_resources(
    configuration: &configuration::Configuration,
    params: PostDevResourcesParams,
) -> Result<models::InlineObject31, Error<PostDevResourcesError>> {
    let uri_str = format!("{}/v1/dev_resources", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };
    req_builder = req_builder.json(&params.post_dev_resources_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject31`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject31`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostDevResourcesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Bulk update dev resources across multiple files.  Ids for dev resources that are successfully updated will show up in the `links_updated` array in the response.  If there are any dev resources that cannot be updated, you may still get a 200 response. These resources will show up in the `errors` array.
pub async fn put_dev_resources(
    configuration: &configuration::Configuration,
    params: PutDevResourcesParams,
) -> Result<models::InlineObject32, Error<PutDevResourcesError>> {
    let uri_str = format!("{}/v1/dev_resources", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };
    req_builder = req_builder.json(&params.put_dev_resources_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject32`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject32`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PutDevResourcesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
