/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`get_developer_logs`]
#[derive(Clone, Debug)]
pub struct GetDeveloperLogsParams {
    pub get_developer_logs_request: Option<models::GetDeveloperLogsRequest>,
}

/// struct for typed errors of method [`get_developer_logs`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetDeveloperLogsError {
    Status400(models::InlineObject47),
    Status401(models::InlineObject48),
    Status403(models::InlineObject50),
    Status429(models::InlineObject54),
    Status500(models::InlineObject57),
    UnknownValue(serde_json::Value),
}

/// Returns a list of developer log entries for REST API and MCP server requests made within the organization. This endpoint requires a plan access token with the `org:developer_log_read` scope.
pub async fn get_developer_logs(
    configuration: &configuration::Configuration,
    params: GetDeveloperLogsParams,
) -> Result<models::InlineObject30, Error<GetDeveloperLogsError>> {
    let uri_str = format!("{}/v1/developer_logs", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };
    req_builder = req_builder.json(&params.get_developer_logs_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject30`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject30`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetDeveloperLogsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
