/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`get_folder_files`]
#[derive(Clone, Debug)]
pub struct GetFolderFilesParams {
    /// ID of the folder to list files from
    pub folder_id: String,
    /// Returns branch metadata in the response for each main file with a branch inside the folder.
    pub branch_data: Option<bool>,
}

/// struct for passing parameters to the method [`get_folder_folders`]
#[derive(Clone, Debug)]
pub struct GetFolderFoldersParams {
    /// ID of the parent folder to list subfolders from
    pub folder_id: String,
}

/// struct for passing parameters to the method [`get_folder_meta`]
#[derive(Clone, Debug)]
pub struct GetFolderMetaParams {
    /// ID of the folder to get metadata for
    pub folder_id: String,
}

/// struct for passing parameters to the method [`get_team_folders`]
#[derive(Clone, Debug)]
pub struct GetTeamFoldersParams {
    /// ID of the team to list folders from
    pub team_id: String,
}

/// struct for typed errors of method [`get_folder_files`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetFolderFilesError {
    Status400(models::InlineObject47),
    Status403(models::InlineObject49),
    Status404(models::InlineObject51),
    Status429(models::InlineObject53),
    Status500(models::InlineObject56),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_folder_folders`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetFolderFoldersError {
    Status400(models::InlineObject47),
    Status403(models::InlineObject49),
    Status404(models::InlineObject51),
    Status429(models::InlineObject53),
    Status500(models::InlineObject56),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_folder_meta`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetFolderMetaError {
    Status403(models::InlineObject49),
    Status404(models::InlineObject51),
    Status429(models::InlineObject53),
    Status500(models::InlineObject56),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_team_folders`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTeamFoldersError {
    Status400(models::InlineObject47),
    Status403(models::InlineObject49),
    Status404(models::InlineObject51),
    Status429(models::InlineObject53),
    Status500(models::InlineObject56),
    UnknownValue(serde_json::Value),
}

/// Get a list of the files directly within the specified folder.
pub async fn get_folder_files(
    configuration: &configuration::Configuration,
    params: GetFolderFilesParams,
) -> Result<models::InlineObject11, Error<GetFolderFilesError>> {
    let uri_str = format!(
        "{}/v2/folders/{folder_id}/files",
        configuration.base_path,
        folder_id = crate::apis::urlencode(params.folder_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.branch_data {
        req_builder = req_builder.query(&[("branch_data", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject11`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject11`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetFolderFilesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get a list of the direct subfolders within the specified folder.
pub async fn get_folder_folders(
    configuration: &configuration::Configuration,
    params: GetFolderFoldersParams,
) -> Result<models::InlineObject9, Error<GetFolderFoldersError>> {
    let uri_str = format!(
        "{}/v2/folders/{folder_id}/folders",
        configuration.base_path,
        folder_id = crate::apis::urlencode(params.folder_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject9`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject9`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetFolderFoldersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get metadata for a folder (name, thumbnail, file count, timestamps) without enumerating its files.
pub async fn get_folder_meta(
    configuration: &configuration::Configuration,
    params: GetFolderMetaParams,
) -> Result<models::InlineObject10, Error<GetFolderMetaError>> {
    let uri_str = format!(
        "{}/v2/folders/{folder_id}/meta",
        configuration.base_path,
        folder_id = crate::apis::urlencode(params.folder_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject10`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject10`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetFolderMetaError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get a list of the top-level folders (previously called \"projects\") within the specified team. Subfolders can be traversed with the GET /v2/folders/{folder_id}/folders endpoint. It is not possible to programmatically obtain team IDs. To obtain a team ID, navigate to the team page in the Figma file browser. The team ID is present in the URL after the word team. For example, in `https://www.figma.com/files/181033233908053158/team/1535685101263221741`, the team ID is `1535685101263221741`.
pub async fn get_team_folders(
    configuration: &configuration::Configuration,
    params: GetTeamFoldersParams,
) -> Result<models::InlineObject8, Error<GetTeamFoldersError>> {
    let uri_str = format!(
        "{}/v2/teams/{team_id}/folders",
        configuration.base_path,
        team_id = crate::apis::urlencode(params.team_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject8`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject8`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetTeamFoldersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
