/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`get_library_analytics_component_actions`]
#[derive(Clone, Debug)]
pub struct GetLibraryAnalyticsComponentActionsParams {
    /// File key of the library to fetch analytics data for.
    pub file_key: String,
    /// A dimension to group returned analytics data by.
    pub group_by: String,
    /// Cursor indicating what page of data to fetch. Obtained from prior API call.
    pub cursor: Option<String>,
    /// ISO 8601 date string (YYYY-MM-DD) of the earliest week to include. Dates are rounded back to the nearest start of a week. Defaults to one year prior.
    pub start_date: Option<String>,
    /// ISO 8601 date string (YYYY-MM-DD) of the latest week to include. Dates are rounded forward to the nearest end of a week. Defaults to the latest computed week.
    pub end_date: Option<String>,
}

/// struct for passing parameters to the method [`get_library_analytics_component_usages`]
#[derive(Clone, Debug)]
pub struct GetLibraryAnalyticsComponentUsagesParams {
    /// File key of the library to fetch analytics data for.
    pub file_key: String,
    /// A dimension to group returned analytics data by.
    pub group_by: String,
    /// Cursor indicating what page of data to fetch. Obtained from prior API call.
    pub cursor: Option<String>,
}

/// struct for passing parameters to the method [`get_library_analytics_style_actions`]
#[derive(Clone, Debug)]
pub struct GetLibraryAnalyticsStyleActionsParams {
    /// File key of the library to fetch analytics data for.
    pub file_key: String,
    /// A dimension to group returned analytics data by.
    pub group_by: String,
    /// Cursor indicating what page of data to fetch. Obtained from prior API call.
    pub cursor: Option<String>,
    /// ISO 8601 date string (YYYY-MM-DD) of the earliest week to include. Dates are rounded back to the nearest start of a week. Defaults to one year prior.
    pub start_date: Option<String>,
    /// ISO 8601 date string (YYYY-MM-DD) of the latest week to include. Dates are rounded forward to the nearest end of a week. Defaults to the latest computed week.
    pub end_date: Option<String>,
}

/// struct for passing parameters to the method [`get_library_analytics_style_usages`]
#[derive(Clone, Debug)]
pub struct GetLibraryAnalyticsStyleUsagesParams {
    /// File key of the library to fetch analytics data for.
    pub file_key: String,
    /// A dimension to group returned analytics data by.
    pub group_by: String,
    /// Cursor indicating what page of data to fetch. Obtained from prior API call.
    pub cursor: Option<String>,
}

/// struct for passing parameters to the method [`get_library_analytics_variable_actions`]
#[derive(Clone, Debug)]
pub struct GetLibraryAnalyticsVariableActionsParams {
    /// File key of the library to fetch analytics data for.
    pub file_key: String,
    /// A dimension to group returned analytics data by.
    pub group_by: String,
    /// Cursor indicating what page of data to fetch. Obtained from prior API call.
    pub cursor: Option<String>,
    /// ISO 8601 date string (YYYY-MM-DD) of the earliest week to include. Dates are rounded back to the nearest start of a week. Defaults to one year prior.
    pub start_date: Option<String>,
    /// ISO 8601 date string (YYYY-MM-DD) of the latest week to include. Dates are rounded forward to the nearest end of a week. Defaults to the latest computed week.
    pub end_date: Option<String>,
}

/// struct for passing parameters to the method [`get_library_analytics_variable_usages`]
#[derive(Clone, Debug)]
pub struct GetLibraryAnalyticsVariableUsagesParams {
    /// File key of the library to fetch analytics data for.
    pub file_key: String,
    /// A dimension to group returned analytics data by.
    pub group_by: String,
    /// Cursor indicating what page of data to fetch. Obtained from prior API call.
    pub cursor: Option<String>,
}

/// struct for typed errors of method [`get_library_analytics_component_actions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLibraryAnalyticsComponentActionsError {
    Status400(models::InlineObject47),
    Status401(models::InlineObject48),
    Status403(models::InlineObject50),
    Status429(models::InlineObject54),
    Status500(models::InlineObject57),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_library_analytics_component_usages`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLibraryAnalyticsComponentUsagesError {
    Status400(models::InlineObject47),
    Status401(models::InlineObject48),
    Status403(models::InlineObject50),
    Status429(models::InlineObject54),
    Status500(models::InlineObject57),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_library_analytics_style_actions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLibraryAnalyticsStyleActionsError {
    Status400(models::InlineObject47),
    Status401(models::InlineObject48),
    Status403(models::InlineObject50),
    Status429(models::InlineObject54),
    Status500(models::InlineObject57),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_library_analytics_style_usages`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLibraryAnalyticsStyleUsagesError {
    Status400(models::InlineObject47),
    Status401(models::InlineObject48),
    Status403(models::InlineObject50),
    Status429(models::InlineObject54),
    Status500(models::InlineObject57),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_library_analytics_variable_actions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLibraryAnalyticsVariableActionsError {
    Status400(models::InlineObject47),
    Status401(models::InlineObject48),
    Status403(models::InlineObject50),
    Status429(models::InlineObject54),
    Status500(models::InlineObject57),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_library_analytics_variable_usages`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLibraryAnalyticsVariableUsagesError {
    Status400(models::InlineObject47),
    Status401(models::InlineObject48),
    Status403(models::InlineObject50),
    Status429(models::InlineObject54),
    Status500(models::InlineObject57),
    UnknownValue(serde_json::Value),
}

/// Returns a list of library analytics component actions data broken down by the requested dimension.
pub async fn get_library_analytics_component_actions(
    configuration: &configuration::Configuration,
    params: GetLibraryAnalyticsComponentActionsParams,
) -> Result<models::InlineObject39, Error<GetLibraryAnalyticsComponentActionsError>> {
    let uri_str = format!(
        "{}/v1/analytics/libraries/{file_key}/component/actions",
        configuration.base_path,
        file_key = crate::apis::urlencode(params.file_key)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("group_by", &params.group_by.to_string())]);
    if let Some(ref param_value) = params.start_date {
        req_builder = req_builder.query(&[("start_date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.end_date {
        req_builder = req_builder.query(&[("end_date", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject39`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject39`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLibraryAnalyticsComponentActionsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Returns a list of library analytics component usage data broken down by the requested dimension.
pub async fn get_library_analytics_component_usages(
    configuration: &configuration::Configuration,
    params: GetLibraryAnalyticsComponentUsagesParams,
) -> Result<models::InlineObject40, Error<GetLibraryAnalyticsComponentUsagesError>> {
    let uri_str = format!(
        "{}/v1/analytics/libraries/{file_key}/component/usages",
        configuration.base_path,
        file_key = crate::apis::urlencode(params.file_key)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("group_by", &params.group_by.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject40`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject40`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLibraryAnalyticsComponentUsagesError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Returns a list of library analytics style actions data broken down by the requested dimension.
pub async fn get_library_analytics_style_actions(
    configuration: &configuration::Configuration,
    params: GetLibraryAnalyticsStyleActionsParams,
) -> Result<models::InlineObject41, Error<GetLibraryAnalyticsStyleActionsError>> {
    let uri_str = format!(
        "{}/v1/analytics/libraries/{file_key}/style/actions",
        configuration.base_path,
        file_key = crate::apis::urlencode(params.file_key)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("group_by", &params.group_by.to_string())]);
    if let Some(ref param_value) = params.start_date {
        req_builder = req_builder.query(&[("start_date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.end_date {
        req_builder = req_builder.query(&[("end_date", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject41`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject41`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLibraryAnalyticsStyleActionsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Returns a list of library analytics style usage data broken down by the requested dimension.
pub async fn get_library_analytics_style_usages(
    configuration: &configuration::Configuration,
    params: GetLibraryAnalyticsStyleUsagesParams,
) -> Result<models::InlineObject42, Error<GetLibraryAnalyticsStyleUsagesError>> {
    let uri_str = format!(
        "{}/v1/analytics/libraries/{file_key}/style/usages",
        configuration.base_path,
        file_key = crate::apis::urlencode(params.file_key)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("group_by", &params.group_by.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject42`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject42`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLibraryAnalyticsStyleUsagesError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Returns a list of library analytics variable actions data broken down by the requested dimension.
pub async fn get_library_analytics_variable_actions(
    configuration: &configuration::Configuration,
    params: GetLibraryAnalyticsVariableActionsParams,
) -> Result<models::InlineObject43, Error<GetLibraryAnalyticsVariableActionsError>> {
    let uri_str = format!(
        "{}/v1/analytics/libraries/{file_key}/variable/actions",
        configuration.base_path,
        file_key = crate::apis::urlencode(params.file_key)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("group_by", &params.group_by.to_string())]);
    if let Some(ref param_value) = params.start_date {
        req_builder = req_builder.query(&[("start_date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.end_date {
        req_builder = req_builder.query(&[("end_date", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject43`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject43`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLibraryAnalyticsVariableActionsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Returns a list of library analytics variable usage data broken down by the requested dimension.
pub async fn get_library_analytics_variable_usages(
    configuration: &configuration::Configuration,
    params: GetLibraryAnalyticsVariableUsagesParams,
) -> Result<models::InlineObject44, Error<GetLibraryAnalyticsVariableUsagesError>> {
    let uri_str = format!(
        "{}/v1/analytics/libraries/{file_key}/variable/usages",
        configuration.base_path,
        file_key = crate::apis::urlencode(params.file_key)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("group_by", &params.group_by.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject44`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject44`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLibraryAnalyticsVariableUsagesError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
