/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`get_o_embed`]
#[derive(Clone, Debug)]
pub struct GetOEmbedParams {
    /// The URL of the Figma file or published Make site to retrieve oEmbed data for.
    pub url: String,
    /// Maximum width of the embed in pixels. Defaults to 800. The response width will be adjusted to maintain a 16:9 aspect ratio with maxheight.
    pub maxwidth: Option<i32>,
    /// Maximum height of the embed in pixels. Defaults to 450. The response height will be adjusted to maintain a 16:9 aspect ratio with maxwidth.
    pub maxheight: Option<i32>,
}

/// struct for typed errors of method [`get_o_embed`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetOEmbedError {
    Status400(models::InlineObject47),
    Status404(models::InlineObject51),
    Status429(models::InlineObject53),
    Status501(models::InlineObject55),
    UnknownValue(serde_json::Value),
}

/// Returns oEmbed data for a Figma file or published Make site URL, following the [oEmbed specification](https://oembed.com/).
pub async fn get_o_embed(
    configuration: &configuration::Configuration,
    params: GetOEmbedParams,
) -> Result<models::InlineObject45, Error<GetOEmbedError>> {
    let uri_str = format!("{}/v1/oembed", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("url", &params.url.to_string())]);
    if let Some(ref param_value) = params.maxwidth {
        req_builder = req_builder.query(&[("maxwidth", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.maxheight {
        req_builder = req_builder.query(&[("maxheight", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Figma-Token", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InlineObject45`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InlineObject45`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetOEmbedError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
