/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AiUsageDailyRow : A single per-user, per-day AI credit usage aggregate for the plan.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiUsageDailyRow {
    /// The id of the plan the usage belongs to.
    #[serde(rename = "plan_id")]
    pub plan_id: String,
    /// The id of the Figma user that consumed the credits.
    #[serde(rename = "user_id")]
    pub user_id: String,
    /// The email of the Figma user that consumed the credits, or `null` when the user's email could not be resolved (e.g. a deleted user).
    #[serde(
        rename = "user_email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_email: Option<Option<String>>,
    /// The calendar date (UTC) of the aggregated usage, in `YYYY-MM-DD` format.
    #[serde(rename = "day")]
    pub day: String,
    /// The editor the AI action was associated with. `not_applicable` when the underlying AI action had no associated file.
    #[serde(rename = "editor_type")]
    pub editor_type: EditorType,
    /// The sum of seat-level (per-user-allocated) credits consumed for this day, user, and editor type.
    #[serde(rename = "seat_credits_sum")]
    pub seat_credits_sum: i32,
    /// The sum of plan-level (shared pool) credits consumed for this day, user, and editor type.
    #[serde(rename = "plan_credits_sum")]
    pub plan_credits_sum: i32,
    /// The id of the workspace the usage was attributed to, or `null` when the usage had no associated workspace.
    #[serde(
        rename = "workspace_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub workspace_id: Option<Option<String>>,
    /// The name of the workspace the usage was attributed to, or `null` when the usage had no associated workspace.
    #[serde(
        rename = "workspace_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub workspace_name: Option<Option<String>>,
    /// The id of the team the usage was attributed to, or `null` when the usage had no associated team.
    #[serde(
        rename = "team_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub team_id: Option<Option<String>>,
    /// The name of the team the usage was attributed to, or `null` when the usage had no associated team.
    #[serde(
        rename = "team_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub team_name: Option<Option<String>>,
    /// The id of the license group the usage was attributed to, or `null` when the usage had no associated license group.
    #[serde(
        rename = "license_group_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub license_group_id: Option<Option<String>>,
    /// The name of the license group the usage was attributed to, or `null` when the usage had no associated license group.
    #[serde(
        rename = "license_group_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub license_group_name: Option<Option<String>>,
    /// The start of the plan-scoped metering period this usage belongs to, as an RFC 3339 UTC timestamp (e.g. `2026-05-01T00:00:00Z`).
    #[serde(rename = "metering_period_start")]
    pub metering_period_start: String,
    /// The end of the plan-scoped metering period this usage belongs to, as an RFC 3339 UTC timestamp (e.g. `2026-06-01T00:00:00Z`).
    #[serde(rename = "metering_period_end")]
    pub metering_period_end: String,
}

impl AiUsageDailyRow {
    /// A single per-user, per-day AI credit usage aggregate for the plan.
    pub fn new(
        plan_id: String,
        user_id: String,
        day: String,
        editor_type: EditorType,
        seat_credits_sum: i32,
        plan_credits_sum: i32,
        metering_period_start: String,
        metering_period_end: String,
    ) -> AiUsageDailyRow {
        AiUsageDailyRow {
            plan_id,
            user_id,
            user_email: None,
            day,
            editor_type,
            seat_credits_sum,
            plan_credits_sum,
            workspace_id: None,
            workspace_name: None,
            team_id: None,
            team_name: None,
            license_group_id: None,
            license_group_name: None,
            metering_period_start,
            metering_period_end,
        }
    }
}
/// The editor the AI action was associated with. `not_applicable` when the underlying AI action had no associated file.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EditorType {
    #[serde(rename = "design")]
    Design,
    #[serde(rename = "figjam")]
    Figjam,
    #[serde(rename = "slides")]
    Slides,
    #[serde(rename = "sites")]
    Sites,
    #[serde(rename = "buzz")]
    Buzz,
    #[serde(rename = "make")]
    Make,
    #[serde(rename = "not_applicable")]
    NotApplicable,
}

impl Default for EditorType {
    fn default() -> EditorType {
        Self::Design
    }
}
