/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.38.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeveloperLogResource : The resource accessed by the request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeveloperLogResource {
    /// The ID or key of the resource. For files this is the file key; for teams and projects this is the numeric ID. Null for requests without an associated resources (e.g. activity logs).
    #[serde(
        rename = "id_or_key",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id_or_key: Option<Option<String>>,
    /// The name of the resource; null for requests without an associated resource (e.g. activity logs).
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    /// The type of resource; null for requests without an associated resource (e.g. activity logs).
    #[serde(
        rename = "type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub r#type: Option<Option<Type>>,
    /// The ID of the organization associated with the request (e.g. that owns the resource).
    #[serde(rename = "org_id")]
    pub org_id: String,
}

impl DeveloperLogResource {
    /// The resource accessed by the request.
    pub fn new(org_id: String) -> DeveloperLogResource {
        DeveloperLogResource {
            id_or_key: None,
            name: None,
            r#type: None,
            org_id,
        }
    }
}
/// The type of resource; null for requests without an associated resource (e.g. activity logs).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file")]
    File,
    #[serde(rename = "team")]
    Team,
    #[serde(rename = "project")]
    Project,
}

impl Default for Type {
    fn default() -> Type {
        Self::File
    }
}
