/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.38.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeveloperLog : A log entry from the Developer Log, representing a REST API or MCP server request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeveloperLog {
    /// The unique identifier of the log entry.
    #[serde(rename = "uuid")]
    pub uuid: String,
    /// The ISO 8601 timestamp of when the request was made.
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "action")]
    pub action: Box<models::DeveloperLogAction>,
    #[serde(rename = "actor")]
    pub actor: Box<models::DeveloperLogActor>,
    #[serde(rename = "resource")]
    pub resource: Box<models::DeveloperLogResource>,
    #[serde(rename = "context")]
    pub context: Box<models::DeveloperLogContext>,
}

impl DeveloperLog {
    /// A log entry from the Developer Log, representing a REST API or MCP server request.
    pub fn new(
        uuid: String,
        timestamp: String,
        action: models::DeveloperLogAction,
        actor: models::DeveloperLogActor,
        resource: models::DeveloperLogResource,
        context: models::DeveloperLogContext,
    ) -> DeveloperLog {
        DeveloperLog {
            uuid,
            timestamp,
            action: Box::new(action),
            actor: Box::new(actor),
            resource: Box::new(resource),
            context: Box::new(context),
        }
    }
}
