/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeveloperLogContext : Context about the request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeveloperLogContext {
    /// The IP address of the client that made the request.
    #[serde(rename = "ip_address")]
    pub ip_address: String,
    /// The city of the client, if available.
    #[serde(
        rename = "city",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub city: Option<Option<String>>,
    /// The region of the client, if available.
    #[serde(
        rename = "country_region",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub country_region: Option<Option<String>>,
    /// The country of the client, if available.
    #[serde(
        rename = "country",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub country: Option<Option<String>>,
}

impl DeveloperLogContext {
    /// Context about the request.
    pub fn new(ip_address: String) -> DeveloperLogContext {
        DeveloperLogContext {
            ip_address,
            city: None,
            country_region: None,
            country: None,
        }
    }
}
