/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeveloperLogAction : The API endpoint or tool that was called.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeveloperLogAction {
    /// The route path (for REST API requests) or tool name (for MCP server calls).
    #[serde(rename = "event_name")]
    pub event_name: String,
    /// The source of the event.
    #[serde(rename = "event_source")]
    pub event_source: EventSource,
}

impl DeveloperLogAction {
    /// The API endpoint or tool that was called.
    pub fn new(event_name: String, event_source: EventSource) -> DeveloperLogAction {
        DeveloperLogAction {
            event_name,
            event_source,
        }
    }
}
/// The source of the event.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventSource {
    #[serde(rename = "rest_api")]
    RestApi,
    #[serde(rename = "mcp_server")]
    McpServer,
}

impl Default for EventSource {
    fn default() -> EventSource {
        Self::RestApi
    }
}
