/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeveloperLogActor : The token used and associated user for the request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeveloperLogActor {
    /// The ID of the user who made the request; null for requests made with plan access tokens, as there is no associated user.
    #[serde(
        rename = "user_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_id: Option<Option<String>>,
    /// The name of the user who made the request; null for requests made with plan access tokens, as there is no associated user.
    #[serde(
        rename = "user_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_name: Option<Option<String>>,
    /// The email of the user who made the request; null for requests made with plan access tokens, as there is no associated user.
    #[serde(
        rename = "user_email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_email: Option<Option<String>>,
    /// The name of the token, or the OAuth app name for OAuth tokens.
    #[serde(rename = "token_name")]
    pub token_name: String,
    /// The type of token used for authentication.
    #[serde(rename = "token_type")]
    pub token_type: TokenType,
}

impl DeveloperLogActor {
    /// The token used and associated user for the request.
    pub fn new(token_name: String, token_type: TokenType) -> DeveloperLogActor {
        DeveloperLogActor {
            user_id: None,
            user_name: None,
            user_email: None,
            token_name,
            token_type,
        }
    }
}
/// The type of token used for authentication.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TokenType {
    #[serde(rename = "developer_token")]
    DeveloperToken,
    #[serde(rename = "plan_access_token")]
    PlanAccessToken,
    #[serde(rename = "oauth_token")]
    OauthToken,
}

impl Default for TokenType {
    fn default() -> TokenType {
        Self::DeveloperToken
    }
}
