/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Folder : A Folder (previously called a \"Project\") is a collection of files and subfolders. Folders can be nested; a folder's parent is identified by `parent_folder_id`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Folder {
    /// The ID of the folder.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the folder.
    #[serde(rename = "name")]
    pub name: String,
    /// The ID of the folder's parent folder, or null if the folder is a top-level folder in the team.
    #[serde(rename = "parent_folder_id", deserialize_with = "Option::deserialize")]
    pub parent_folder_id: Option<String>,
}

impl Folder {
    /// A Folder (previously called a \"Project\") is a collection of files and subfolders. Folders can be nested; a folder's parent is identified by `parent_folder_id`.
    pub fn new(id: String, name: String, parent_folder_id: Option<String>) -> Folder {
        Folder {
            id,
            name,
            parent_folder_id,
        }
    }
}
