/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDeveloperLogsRequest {
    /// Filter by the type of token used for authentication.
    #[serde(rename = "token_type", skip_serializing_if = "Option::is_none")]
    pub token_type: Option<TokenType>,
    /// Filter by token value(s). Multiple values can be separated by commas.
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// Filter by token name prefix(es). Multiple values can be separated by commas.
    #[serde(rename = "token_name", skip_serializing_if = "Option::is_none")]
    pub token_name: Option<String>,
    /// Filter by user email prefix(es). Multiple values can be separated by commas.
    #[serde(rename = "user_email", skip_serializing_if = "Option::is_none")]
    pub user_email: Option<String>,
    /// Filter by IP address prefix(es). Multiple values can be separated by commas.
    #[serde(rename = "ip_address", skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    /// Filter by event source.
    #[serde(rename = "event_source", skip_serializing_if = "Option::is_none")]
    pub event_source: Option<EventSource>,
    /// Filter by date range.
    #[serde(rename = "date_range", skip_serializing_if = "Option::is_none")]
    pub date_range: Option<DateRange>,
    /// Maximum number of entries to return.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<u8>,
    /// A cursor returned from a previous request, used for pagination.
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl GetDeveloperLogsRequest {
    pub fn new() -> GetDeveloperLogsRequest {
        GetDeveloperLogsRequest {
            token_type: None,
            token: None,
            token_name: None,
            user_email: None,
            ip_address: None,
            event_source: None,
            date_range: None,
            limit: None,
            cursor: None,
        }
    }
}
/// Filter by the type of token used for authentication.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TokenType {
    #[serde(rename = "plan_access_token")]
    PlanAccessToken,
    #[serde(rename = "developer_token")]
    DeveloperToken,
    #[serde(rename = "oauth_token")]
    OauthToken,
}

impl Default for TokenType {
    fn default() -> TokenType {
        Self::PlanAccessToken
    }
}
/// Filter by event source.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventSource {
    #[serde(rename = "rest_api")]
    RestApi,
    #[serde(rename = "mcp_server")]
    McpServer,
}

impl Default for EventSource {
    fn default() -> EventSource {
        Self::RestApi
    }
}
/// Filter by date range.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DateRange {
    #[serde(rename = "last_24h")]
    Last24h,
    #[serde(rename = "last_7d")]
    Last7d,
    #[serde(rename = "last_30d")]
    Last30d,
}

impl Default for DateRange {
    fn default() -> DateRange {
        Self::Last24h
    }
}
