/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InlineObject40Rows : An array of analytics data.
/// An array of analytics data.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InlineObject40Rows {
    Array(Vec<models::LibraryAnalyticsComponentUsagesByAsset>),
    Array2(Vec<models::LibraryAnalyticsComponentUsagesByFile>),
}

impl Default for InlineObject40Rows {
    fn default() -> Self {
        Self::Array(Default::default())
    }
}
