/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.38.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject25Meta {
    /// An array of developer log entries sorted by timestamp in descending order.
    #[serde(rename = "items")]
    pub items: Vec<models::DeveloperLog>,
    /// A cursor for pagination. Pass this value as the `cursor` parameter in the next request to retrieve the next page of results. `null` when there are no more results.
    #[serde(
        rename = "cursor",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cursor: Option<Option<String>>,
    /// Whether there are more results available after this page.
    #[serde(rename = "has_more")]
    pub has_more: bool,
}

impl InlineObject25Meta {
    pub fn new(items: Vec<models::DeveloperLog>, has_more: bool) -> InlineObject25Meta {
        InlineObject25Meta {
            items,
            cursor: None,
            has_more,
        }
    }
}
