/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject8 {
    /// The team's name.
    #[serde(rename = "name")]
    pub name: String,
    /// An array of the team's top-level folders. Each folder's `parent_folder_id` is null.
    #[serde(rename = "folders")]
    pub folders: Vec<models::Folder>,
}

impl InlineObject8 {
    pub fn new(name: String, folders: Vec<models::Folder>) -> InlineObject8 {
        InlineObject8 { name, folders }
    }
}
