/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject31 {
    /// Per-user, per-day AI credit usage aggregates, ordered by `day`, then user, then `editor_type`.
    #[serde(rename = "rows")]
    pub rows: Vec<models::AiUsageDailyRow>,
    /// An opaque cursor to pass as the `cursor` query parameter to fetch the next page. Empty when there are no more pages.
    #[serde(rename = "next_cursor")]
    pub next_cursor: String,
    /// Whether there is a next page of results to fetch.
    #[serde(rename = "has_next_page")]
    pub has_next_page: bool,
}

impl InlineObject31 {
    pub fn new(
        rows: Vec<models::AiUsageDailyRow>,
        next_cursor: String,
        has_next_page: bool,
    ) -> InlineObject31 {
        InlineObject31 {
            rows,
            next_cursor,
            has_next_page,
        }
    }
}
