/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject35 {
    /// The response status code.
    #[serde(skip)]
    pub status: Status,
    /// For successful requests, this value is always `false`.
    #[serde(skip)]
    pub error: Error,
    #[serde(rename = "meta")]
    pub meta: Box<models::InlineObject35Meta>,
}

impl InlineObject35 {
    pub fn new(status: Status, error: Error, meta: models::InlineObject35Meta) -> InlineObject35 {
        InlineObject35 {
            status,
            error,
            meta: Box::new(meta),
        }
    }
}
/// The response status code.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "200")]
    Variant200,
}

impl Default for Status {
    fn default() -> Status {
        Self::Variant200
    }
}
/// For successful requests, this value is always `false`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "false")]
    False,
}

impl Default for Error {
    fn default() -> Error {
        Self::False
    }
}
