/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.38.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject50 {
    /// Status code
    #[serde(skip)]
    pub status: Status,
    /// A string describing the error
    #[serde(rename = "err")]
    pub err: String,
}

impl InlineObject50 {
    pub fn new(status: Status, err: String) -> InlineObject50 {
        InlineObject50 { status, err }
    }
}
/// Status code
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "500")]
    Variant500,
}

impl Default for Status {
    fn default() -> Status {
        Self::Variant500
    }
}
