/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject10 {
    /// The ID of the folder.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the folder.
    #[serde(rename = "name")]
    pub name: String,
    /// A URL to a thumbnail image of the folder. Null if the folder has no files.
    #[serde(rename = "thumbnail_url", deserialize_with = "Option::deserialize")]
    pub thumbnail_url: Option<String>,
    /// The number of files in the folder.
    #[serde(rename = "file_count")]
    pub file_count: i32,
    /// The UTC ISO 8601 time at which the folder was last updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    /// The UTC ISO 8601 time at which the folder was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl InlineObject10 {
    pub fn new(
        id: String,
        name: String,
        thumbnail_url: Option<String>,
        file_count: i32,
        updated_at: String,
        created_at: String,
    ) -> InlineObject10 {
        InlineObject10 {
            id,
            name,
            thumbnail_url,
            file_count,
            updated_at,
            created_at,
        }
    }
}
