/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.38.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject30 {
    /// An array of dev resources.
    #[serde(rename = "dev_resources")]
    pub dev_resources: Vec<models::DevResource>,
}

impl InlineObject30 {
    pub fn new(dev_resources: Vec<models::DevResource>) -> InlineObject30 {
        InlineObject30 { dev_resources }
    }
}
