/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject45 {
    /// The oEmbed specification version. Always \"1.0\".
    #[serde(rename = "version")]
    pub version: String,
    /// The oEmbed response type. Always \"rich\".
    #[serde(rename = "type")]
    pub r#type: String,
    /// The title of the Figma file or published Make site.
    #[serde(rename = "title")]
    pub title: String,
    /// The key of the Figma file. Not present for published Makes
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The canonical URL of the resource.
    #[serde(rename = "url")]
    pub url: String,
    /// The name of the content provider. Always \"Figma\" or \"Make\".
    #[serde(rename = "provider_name")]
    pub provider_name: String,
    /// The URL of the content provider's website. Always \"https://www.figma.com\".
    #[serde(rename = "provider_url")]
    pub provider_url: String,
    /// Suggested cache lifetime for this response in seconds. Always 3600.
    #[serde(rename = "cache_age")]
    pub cache_age: i32,
    /// Width of the embed in pixels.
    #[serde(rename = "width")]
    pub width: i32,
    /// Height of the embed in pixels.
    #[serde(rename = "height")]
    pub height: i32,
    /// The HTML for embedding the file. Contains an iframe pointing to the Figma embed URL.
    #[serde(rename = "html")]
    pub html: String,
    /// Only present and \"true\" when the resource is a published Make.
    #[serde(rename = "is_published_site", skip_serializing_if = "Option::is_none")]
    pub is_published_site: Option<bool>,
    /// The name of the folder containing the file, if the file resides in a folder.
    #[serde(rename = "folder_name", skip_serializing_if = "Option::is_none")]
    pub folder_name: Option<String>,
    /// URL of a thumbnail image for the file.
    #[serde(rename = "thumbnail_url", skip_serializing_if = "Option::is_none")]
    pub thumbnail_url: Option<String>,
    /// Width of the thumbnail image in pixels.
    #[serde(rename = "thumbnail_width", skip_serializing_if = "Option::is_none")]
    pub thumbnail_width: Option<i32>,
    /// Height of the thumbnail image in pixels.
    #[serde(rename = "thumbnail_height", skip_serializing_if = "Option::is_none")]
    pub thumbnail_height: Option<i32>,
}

impl InlineObject45 {
    pub fn new(
        version: String,
        r#type: String,
        title: String,
        url: String,
        provider_name: String,
        provider_url: String,
        cache_age: i32,
        width: i32,
        height: i32,
        html: String,
    ) -> InlineObject45 {
        InlineObject45 {
            version,
            r#type,
            title,
            key: None,
            url,
            provider_name,
            provider_url,
            cache_age,
            width,
            height,
            html,
            is_published_site: None,
            folder_name: None,
            thumbnail_url: None,
            thumbnail_width: None,
            thumbnail_height: None,
        }
    }
}
