/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://developers.figma.com/docs/rest-api/).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.42.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject7 {
    /// The project's name.
    #[serde(rename = "name")]
    pub name: String,
    /// An array of files.
    #[serde(rename = "files")]
    pub files: Vec<models::InlineObject7FilesInner>,
}

impl InlineObject7 {
    pub fn new(name: String, files: Vec<models::InlineObject7FilesInner>) -> InlineObject7 {
        InlineObject7 { name, files }
    }
}
